// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bogagqgsmckhvjcsysjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZ2FncWdzbWNraHZqY3N5c2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzIwNTUsImV4cCI6MjA2NTUwODA1NX0.jiXbXc-LUJxLUBJ2NsKsuEiwI3SUOZlf9yz-1DNmFJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});